[project]
name = "who_fi"
version = "0.1.0"
description = "A reimplementation of the WhoFi paper for person re-identification using Wi-Fi CSI."
dependencies = [
    "beautifulsoup4==4.13.4",
    "certifi==2025.8.3",
    "charset-normalizer==3.4.3",
    "filelock==3.13.1",
    "fsspec==2024.6.1",
    "gdown==5.2.0",
    "idna==3.10",
    "jinja2==3.1.4",
    "markupsafe==2.1.5",
    "mpmath==1.3.0",
    "networkx==3.3",
    "numpy==2.1.2",
    "pysocks==1.7.1",
    "requests==2.32.4",
    "setuptools==70.2.0",
    "soupsieve==2.7",
    "sympy==1.13.3",
    "torch @ https://download.pytorch.org/whl/cpu/torch-2.8.0%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=d16223b313462f243f78acef98a85354e6a4b8c9b83b38c3866b865f3f019f2d",
    "tqdm==4.67.1",
    "typing-extensions==4.12.2",
    "urllib3==2.5.0"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
